<?php
/**
 * Created by PhpStorm.
 * User: Gabriel
 * Date: 24/01/2018
 * Time: 02:40 PM
 */

namespace framework\modules\configuration\model;



use framework\modules\base\model\Base;
use framework\modules\fileStorage\model\FileStorage;
use framework\services\UrlService;

class Configuration extends FileStorage
{
    function model()
    {
        $model = parent::model();

        $model["_id"]="";
        //TESTING,DEVELOPMENT or PRODUCTION
        $model["env"] ="DEVELOPMENT";

        $model["active"] = false;

        //Email parameters
        $model["email_host"] ="";
        $model["email_smtp_auth"]=true;
        $model["email_smtp_secure"]="tls";
        $model["email_username"] ="";
        $model["email_password"]="";
        $model["email_port"]=587;


        //App parameters
        $model["app_name"]="";
        $model["app_url"]="";
        //TODO: set an id for every app that is deployed
        $model["app_id"] ="";

        //Site parameters
        $model["site_name"]="";
        $model["site_url"] = UrlService::CurrentUrl();


        //DB config
        $model["db_name"]="";
        $model["db_user"]="";
        $model["db_pass"]="";
        $model["db_port"]="";
        $model["db_host"]="";



        return $model;
    }



    public function rules()
    {
        $rules = parent::rules();

        $rules[] = ['InRange','db_port',[1,65535,true] ,"portRangeAllowed:1,65535"];

        $rules[] = ['MatchesExp','app_name',['^[a-zA-Z0-9_. -]{5,30}$'],'appNameNotAllowed'];

        //$rules[] = ["IsUrl",'app_url',[],'invalidUrl'];

        $rules[] = ["MatchesExp",'site_name',['^[a-zA-Z0-9_. -]{5,40}$',true],'siteNameNotAllowed'];

        $rules[] = ["IsUrl",'site_url',[true],'invalidUrl'];



        $rules[] = ["IsIP",'db_host',[],'invalidIp'];

        $rules[] = ['NotEmpty','db_user',[] ,"shouldntBeEmpty"];

        $rules[] = ['MatchesLength','db_name',[2,100],'lengthBetween:2,100'];



        $rules[] = ["IsEmail","email_username",[],'mainEmailNotValid'];

        $rules[] = ["IsUrl","email_host",[],'invalidUrl'];

        $rules[] = ['InRange','email_port',[1,65535,true] ,"portRangeAllowed:1,65535"];










        return $rules;
    }

    static function BeforeUpdate(Base &$obj)
    {
        parent::BeforeUpdate($obj); // TODO: Change the autogenerated stub
    }



}